let f1 = function (i) { return i * i; };
let f2 = function (i) { return i * i; };
let f3 = (i) => { return i * i; };
let f4 = (i) => { return i * i; };
let f5 = (i) => i * i;
console.log(f1(5));
console.log(f2(6));
console.log(f3(4));
console.log(f4(4));
console.log(f5(4));
